// Auto-generated by scripts/sync-party-logos.mjs
export const PARTY_LOGOS: Record<string, string> = {
  "AVANTE": "/logos/partidos/AVANTE.png",
  "CIDADANIA": "/logos/partidos/CIDADANIA.png",
  "MDB": "/logos/partidos/MDB.png",
  "MISSAO": "/logos/partidos/MISSAO.png",
  "NOVO": "/logos/partidos/NOVO.png",
  "PCDOB": "/logos/partidos/PCDOB.png",
  "PDT": "/logos/partidos/PDT.png",
  "PL": "/logos/partidos/PL.png",
  "PODE": "/logos/partidos/PODE.png",
  "PP": "/logos/partidos/PP.png",
  "PSB": "/logos/partidos/PSB.png",
  "PSD": "/logos/partidos/PSD.png",
  "PSDB": "/logos/partidos/PSDB.png",
  "PSOL": "/logos/partidos/PSOL.png",
  "PT": "/logos/partidos/PT.png",
  "PV": "/logos/partidos/PV.png",
  "REDE": "/logos/partidos/REDE.png",
  "REPUBLICANOS": "/logos/partidos/REPUBLICANOS.png",
  "SOLIDARIEDADE": "/logos/partidos/SOLIDARIEDADE.png",
  "UNIAO": "/logos/partidos/UNIAO.png",
};

